import os
from openai import OpenAI

class InsightSynthesizer:
    def __init__(self):
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def generate_section_narrative(self, section_title, pandas_output, rag_output):
        """
        Merges quantitative stats (Pandas) with qualitative context (RAG).
        """
        
        # 1. Prepare inputs for the LLM
        # Handle cases where one agent might have failed or wasn't needed
        stats_text = pandas_output.get('insight', 'No statistical data available.') if pandas_output else 'N/A'
        context_text = rag_output.get('insight', 'No qualitative context available.') if rag_output else 'N/A'
        
        image_markdown = ""
        if pandas_output and pandas_output.get('image'):
            image_markdown = f"\n\n![{section_title} Chart]({pandas_output['image']})"

        # 2. Construct the Prompt
        # We ask the LLM to act as a reporter connecting the dots
        prompt = f"""
        You are a Senior Business Analyst writing a report for BMW executives.
        
        TASK: Write a cohesive section for "{section_title}".
        
        INPUT DATA:
        1. Quantitative Analysis (Hard Numbers):
        "{stats_text}"
        
        2. Qualitative Context (Features/Specs/Reviews):
        "{context_text}"
        
        INSTRUCTIONS:
        - Combine the numbers and the context into a single flowing narrative.
        - Do not explicitly say "The RAG agent said...".
        - If the qualitative context explains the numbers (e.g., high sales due to specific features), make that connection clear.
        - Keep it professional, concise, and insight-driven.
        - Use Markdown formatting.
        """

        # 3. Generate Narrative
        response = self.client.chat.completions.create(
            model="gpt-5.1",
            messages=[{"role": "system", "content": prompt}]
        )
        
        narrative = response.choices[0].message.content
        
        # 4. Return Final Markdown Block
        final_output = f"## {section_title}\n\n{narrative}{image_markdown}\n\n"
        return final_output

    def compile_final_report(self, sections, filename="final_report.md"):
        """Save all sections to a file."""
        with open(filename, "w", encoding="utf-8") as f:
            f.write("# BMW Global Sales Analysis Report (2020-2024)\n\n")
            f.write("> Generated by AI Multi-Agent System\n\n")
            for section in sections:
                f.write(section)
        
        return os.path.abspath(filename)