import React, { useState, useEffect } from 'react';
import { 
  Upload, 
  BarChart3, 
  Database, 
  BrainCircuit, 
  CheckCircle2, 
  FileJson, 
  Search,
  ArrowRight,
  Layout,
  FileText,
  Code,
  Download,
  Loader2,
  Terminal,
  RefreshCw,
  AlertCircle
} from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';

const WorkflowVisualizer = () => {
  const [activeTab, setActiveTab] = useState(0);
  const [processing, setProcessing] = useState(false);
  
  // Pipeline State
  const [csvFile, setCsvFile] = useState(null);
  const [dataset, setDataset] = useState(null); // The Parsed Real Data
  const [agentOutput, setAgentOutput] = useState(null); // The Calculated Results
  const [report, setReport] = useState(null); // The Final Text

  // --- 1. REAL DATA INGESTION ENGINE ---
  
  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
      setCsvFile(file);
      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        parseCSV(text);
      };
      reader.readAsText(file);
    }
  };

  const parseCSV = (csvText) => {
    const lines = csvText.split('\n');
    const headers = lines[0].split(',').map(h => h.trim());
    
    const parsedData = [];
    // Limit to 50k rows for browser performance if file is huge
    for (let i = 1; i < Math.min(lines.length, 50000); i++) {
        const currentLine = lines[i].split(',');
        if (currentLine.length === headers.length) {
            const row = {};
            headers.forEach((header, index) => {
                let val = currentLine[index]?.trim();
                // Auto-convert numeric columns expected in scripts
                if (['Year', 'Sales_Volume', 'Price_USD', 'Mileage_KM', 'Engine_Size_L'].includes(header)) {
                    val = parseFloat(val) || 0;
                }
                row[header] = val;
            });
            parsedData.push(row);
        }
    }
    setDataset(parsedData);
  };

  // --- 2. AGENT LOGIC SIMULATION (Ported from Python) ---
  
  const runPandasAgent = (data) => {
    // LOGIC PORT: df.groupby('Region')['Sales_Volume'].sum().sort_values(ascending=False)
    
    // 1. Group and Sum
    const regionalSales = data.reduce((acc, curr) => {
      const region = curr['Region'] || 'Unknown';
      const sales = curr['Sales_Volume'] || 0;
      acc[region] = (acc[region] || 0) + sales;
      return acc;
    }, {});

    // 2. Sort (Descending)
    const sortedEntries = Object.entries(regionalSales)
      .sort(([,a], [,b]) => b - a);
      
    // Format for Chart
    const chartData = sortedEntries.map(([name, value]) => ({ name, value }));
    const resultObj = Object.fromEntries(sortedEntries);

    const topRegion = sortedEntries[0][0];
    const topValue = sortedEntries[0][1];
    
    return {
      // Showing the exact code from DualAgentProcess.py
      code: `def execute_task(self, query):\n    # Generated by PandasAgent\n    # Query: "Calculate total sales volume by Region..."\n    result = df.groupby('Region')['Sales_Volume'].sum().sort_values(ascending=False)\n    return result.to_dict()`,
      result: resultObj,
      chartData: chartData,
      insight: `${topRegion} leads sales volume with ${topValue.toLocaleString()} units sold, outperforming the next region by ${((topValue - sortedEntries[1][1])/sortedEntries[1][1] * 100).toFixed(1)}%.`
    };
  };

  const runRAGAgent = (data) => {
    // LOGIC PORT: Retrieval of qualitative data. 
    // Since we can't run ChromaDB in browser, we use the specific queries from ImportConfig.py
    // and extract representative rows from the real data to serve as "Context".

    const sampleEuRow = data.find(r => r.Region === 'Europe' && r.Model?.includes('M5')) || {};
    
    return {
      query: "What specific features or regulations make BMW models popular or unique in Europe?",
      // We pull ACTUAL data points to simulate retrieval context
      retrieval: [
        `Context 1 (Regulatory): High sales of ${data.filter(r => r.Region === 'Europe' && r.Fuel_Type === 'Hybrid').length} Hybrid units in Europe reflects Euro 6 compliance.`,
        `Context 2 (Model Spec): Found ${data.filter(r => r.Model === 'M5').length} M5 sales records. Sample Feature: ${sampleEuRow.Transmission || 'Automatic'} Transmission logic preferred in EU.`,
        `Context 3 (Pricing): Average price in Europe is $${(data.filter(r => r.Region === 'Europe').reduce((a,b)=>a+b.Price_USD,0) / data.filter(r => r.Region === 'Europe').length).toFixed(0)}.`
      ],
      insight: "Analysis of the dataset confirms Europe's preference for Hybrid powertrains (regulatory alignment) and high-performance trims like the M5, supported by the calculated average price point."
    };
  };

  // --- 3. SYNTHESIS ENGINE (Ported from InsightSynthesisEngine.py) ---
  const generateReport = (agents) => {
    const stats = agents.pandas.result;
    const sortedKeys = Object.keys(stats);
    const winner = sortedKeys[0];
    const runnerUp = sortedKeys[1];
    
    // Using the template logic from InsightSynthesisEngine.py
    return `## Regional Performance Drivers

**${winner}** has emerged as the clear market leader in this analysis cycle, recording a total sales volume of **${stats[winner].toLocaleString()} units**.

### Comparative Analysis
This performance significantly outpaces the runner-up, **${runnerUp}** (${stats[runnerUp].toLocaleString()} units).

### Key Drivers (Synthesized Insight)
Merging the quantitative aggregation with context retrieval suggests:
1.  **Volume Driver:** The dominance in ${winner} aligns with the retrieval finding regarding **Hybrid Powertrain uptake** and specific regulatory compliance.
2.  **Market Lag:** The gap between ${winner} and ${runnerUp} (${(stats[winner] - stats[runnerUp]).toLocaleString()} units) indicates distinct market maturity levels.

> **Automated Recommendation:** Focus inventory strategy on the high-performing models identified in the ${winner} region context blocks.`;
  };

  // --- WORKFLOW CONTROLLER ---
  const handleTabChange = (newTab) => {
    if (processing) return;

    // Trigger processing for the new tab
    setActiveTab(newTab);
    setProcessing(true);

    setTimeout(() => {
      if (newTab === 1) {
         // Run Agents on the REAL dataset
         if (dataset) {
            setAgentOutput({
              pandas: runPandasAgent(dataset),
              rag: runRAGAgent(dataset)
            });
         }
      } else if (newTab === 2) {
         // Write report using CURRENT agent output
         if (agentOutput) {
            setReport(generateReport(agentOutput));
         }
      }
      setProcessing(false);
    }, 1500); 
  };

  const tabs = [
    { id: 0, label: 'Import & Config', icon: Upload, color: 'text-blue-600', bg: 'bg-blue-50', border: 'border-blue-200' },
    { id: 1, label: 'Dual-Agent Processing', icon: Layout, color: 'text-indigo-600', bg: 'bg-indigo-50', border: 'border-indigo-200' },
    { id: 2, label: 'Report Synthesis', icon: BrainCircuit, color: 'text-purple-600', bg: 'bg-purple-50', border: 'border-purple-200' },
    { id: 3, label: 'Final Output', icon: CheckCircle2, color: 'text-green-600', bg: 'bg-green-50', border: 'border-green-200' },
  ];

  const COLORS = ['#2563eb', '#10b981', '#f59e0b', '#8b5cf6', '#ef4444'];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 font-sans p-4 md:p-8">
      <div className="max-w-7xl mx-auto">
        
        <header className="mb-8 text-center">
          <h1 className="text-3xl font-bold text-slate-900 mb-2">
            AI Reporting Workflow Engine
          </h1>
          <p className="text-slate-600 flex items-center justify-center gap-2">
            Pipeline Status: <span className="inline-flex items-center gap-1 bg-green-100 text-green-700 px-2 py-1 rounded text-xs font-bold uppercase">Ready <RefreshCw size={10}/></span>
          </p>
        </header>

        {/* TAB NAVIGATION */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => handleTabChange(tab.id)}
              disabled={processing || (tab.id > 0 && !dataset)}
              className={`flex items-center gap-3 p-4 rounded-xl border-2 transition-all duration-300 text-left relative overflow-hidden ${
                activeTab === tab.id 
                  ? `${tab.border} ${tab.bg} shadow-md` 
                  : 'bg-white border-transparent hover:border-slate-200 hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed'
              }`}
            >
              <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${activeTab === tab.id ? 'bg-white' : 'bg-slate-100'}`}>
                <tab.icon size={20} className={activeTab === tab.id ? tab.color : 'text-slate-400'} />
              </div>
              <div className="flex-1">
                <span className={`block text-xs font-bold uppercase tracking-wider ${activeTab === tab.id ? tab.color : 'text-slate-400'}`}>
                  Step {tab.id + 1}
                </span>
                <span className={`block font-semibold ${activeTab === tab.id ? 'text-slate-900' : 'text-slate-500'}`}>
                  {tab.label}
                </span>
              </div>
              {activeTab === tab.id && (
                <div className={`absolute bottom-0 left-0 w-full h-1 ${tab.color.replace('text', 'bg')}`} />
              )}
            </button>
          ))}
        </div>

        {/* MAIN CONTENT STAGE */}
        <div className="relative min-h-[600px]">
          
          {/* TAB 1: IMPORT */}
          {activeTab === 0 && (
            <div className="bg-white rounded-2xl shadow-xl border border-blue-100 p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="flex justify-between items-start mb-6">
                <div>
                   <h2 className="text-2xl font-bold text-slate-900">Data Ingestion Layer</h2>
                   <p className="text-slate-500">Target Config: <code>ImportConfig.py</code></p>
                </div>
                {dataset && (
                  <div className="text-right">
                     <div className="text-3xl font-bold text-blue-600">{dataset.length.toLocaleString()}</div>
                     <div className="text-xs text-slate-500 uppercase font-bold">Rows Loaded</div>
                  </div>
                )}
              </div>

              {!dataset ? (
                <div className="border-2 border-dashed border-slate-300 rounded-xl p-12 text-center hover:bg-slate-50 transition-colors">
                    <div className="w-16 h-16 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
                        <Upload size={32} />
                    </div>
                    <h3 className="text-lg font-bold text-slate-700 mb-2">Upload Source Data</h3>
                    <p className="text-slate-500 mb-6 max-w-md mx-auto">Please upload the <code>BMW sales data (2020-2024).csv</code> file to initialize the pipeline.</p>
                    <input 
                        type="file" 
                        accept=".csv"
                        onChange={handleFileUpload}
                        className="block w-full text-sm text-slate-500
                          file:mr-4 file:py-2 file:px-4
                          file:rounded-full file:border-0
                          file:text-sm file:font-semibold
                          file:bg-blue-600 file:text-white
                          hover:file:bg-blue-700
                          cursor-pointer mx-auto max-w-xs
                        "
                    />
                </div>
              ) : (
                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 overflow-hidden">
                    <div className="flex items-center gap-2 mb-4 text-green-700 font-bold text-sm">
                        <CheckCircle2 size={16} /> Data Parsed Successfully
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left text-sm text-slate-600">
                        <thead className="bg-slate-100 text-slate-700 uppercase text-xs">
                            <tr>
                            {Object.keys(dataset[0]).slice(0, 5).map(h => <th key={h} className="px-4 py-2">{h}</th>)}
                            </tr>
                        </thead>
                        <tbody className="font-mono text-xs">
                            {dataset.slice(0, 5).map((row, i) => (
                            <tr key={i} className="border-b border-slate-200">
                                {Object.values(row).slice(0, 5).map((v, j) => <td key={j} className="px-4 py-2">{v}</td>)}
                            </tr>
                            ))}
                        </tbody>
                        </table>
                    </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: AGENTS */}
          {activeTab === 1 && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
              {/* Pandas Agent */}
              <div className="bg-white rounded-2xl shadow-lg border border-slate-200 flex flex-col">
                <div className="bg-indigo-600 p-4 text-white flex justify-between">
                  <div className="font-bold flex gap-2"><BarChart3/> Pandas Agent</div>
                  <span className="text-xs bg-indigo-500 px-2 py-1 rounded">config: high_level</span>
                </div>
                <div className="p-6 flex-1 flex flex-col gap-4">
                  {agentOutput ? (
                    <>
                      <div className="bg-slate-900 rounded-lg p-4 font-mono text-xs text-green-400 overflow-x-auto">
                        <div className="text-slate-500 mb-2 border-b border-slate-700 pb-1">Executing Logic (Ported to JS)</div>
                        <pre>{agentOutput.pandas.code}</pre>
                      </div>
                      
                      <div className="h-48 w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={agentOutput.pandas.chartData}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                <XAxis dataKey="name" tick={{fontSize: 10}} interval={0} />
                                <YAxis tick={{fontSize: 10}} />
                                <Tooltip />
                                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                                    {agentOutput.pandas.chartData.map((entry, index) => (
                                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                    ))}
                                </Bar>
                            </BarChart>
                        </ResponsiveContainer>
                      </div>

                      <div className="bg-indigo-50 rounded-lg p-4 border border-indigo-100">
                        <div className="text-xs font-bold text-indigo-800 uppercase mb-2">Result Insight</div>
                        <p className="text-sm text-indigo-900">{agentOutput.pandas.insight}</p>
                      </div>
                    </>
                  ) : <div className="h-full flex items-center justify-center"><Loader2 className="animate-spin text-indigo-300"/></div>}
                </div>
              </div>

              {/* RAG Agent */}
              <div className="bg-white rounded-2xl shadow-lg border border-slate-200 flex flex-col">
                <div className="bg-emerald-600 p-4 text-white flex justify-between">
                  <div className="font-bold flex gap-2"><Database/> RAG Agent</div>
                  <span className="text-xs bg-emerald-500 px-2 py-1 rounded">config: detailed</span>
                </div>
                <div className="p-6 flex-1 flex flex-col gap-4">
                  {agentOutput ? (
                    <>
                      <div className="bg-slate-100 p-3 rounded text-sm text-slate-700 font-mono">
                         query: "{agentOutput.rag.query}"
                      </div>
                      <div className="bg-emerald-50 rounded-lg p-4 border border-emerald-100 flex-1">
                        <div className="text-xs font-bold text-emerald-800 uppercase mb-2">Retrieved Context (From Uploaded Data)</div>
                        <ul className="space-y-2">
                           {agentOutput.rag.retrieval.map((txt, i) => (
                             <li key={i} className="text-xs text-emerald-900 bg-white p-2 rounded shadow-sm border-l-4 border-emerald-500">{txt}</li>
                           ))}
                        </ul>
                      </div>
                    </>
                  ) : <div className="h-full flex items-center justify-center"><Loader2 className="animate-spin text-emerald-300"/></div>}
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: SYNTHESIS */}
          {activeTab === 2 && (
            <div className="bg-white rounded-2xl shadow-xl border border-slate-200 p-8 animate-in fade-in slide-in-from-bottom-4 duration-500 min-h-[500px]">
               <div className="flex items-center gap-4 mb-6 border-b border-slate-100 pb-4">
                 <div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center text-purple-600"><BrainCircuit/></div>
                 <h2 className="text-xl font-bold">Insight Synthesis</h2>
               </div>

               {report ? (
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-8 h-full">
                    <div className="space-y-4">
                       <div className="bg-slate-50 p-4 rounded border border-slate-200 text-xs text-slate-500 font-mono h-full">
                          <div className="font-bold mb-2 uppercase text-slate-400">Inputs from Agents</div>
                          <div className="mb-2">PANDAS: {JSON.stringify(agentOutput.pandas.result).substring(0, 100)}...</div>
                          <div>RAG: {agentOutput.rag.retrieval[0]}</div>
                       </div>
                    </div>
                    <div className="bg-white border-2 border-purple-100 rounded-xl p-6 shadow-xl relative">
                       <div className="absolute top-0 right-0 bg-purple-600 text-white text-[10px] uppercase font-bold px-2 py-1 rounded-bl-lg">Generated Output</div>
                       <div className="prose prose-sm prose-slate whitespace-pre-wrap">
                          {report}
                       </div>
                    </div>
                 </div>
               ) : <div className="h-64 flex items-center justify-center"><Loader2 className="animate-spin text-purple-300 w-8 h-8"/></div>}
            </div>
          )}

          {/* TAB 4: DELIVERABLES */}
          {activeTab === 3 && report && (
            <div className="bg-white rounded-2xl shadow-xl border border-slate-200 p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
               <div className="flex justify-between items-center mb-6">
                 <h2 className="text-xl font-bold flex items-center gap-2"><CheckCircle2 className="text-green-600"/> Final Deliverables</h2>
                 <button className="bg-blue-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-bold hover:bg-blue-700 transition-colors">
                    <Download size={16}/> Download Report.pdf
                 </button>
               </div>
               
               <div className="grid grid-cols-1 gap-4">
                  <div className="bg-slate-900 rounded-lg p-6 font-mono text-xs text-blue-300 overflow-auto max-h-[400px]">
                    <pre>{JSON.stringify({
                      meta: { generated_at: new Date().toISOString(), source: "Live_Client_Engine" },
                      data_summary: { total_rows: dataset.length, top_region: agentOutput.pandas.insight },
                      final_narrative: report
                    }, null, 2)}</pre>
                  </div>
               </div>
            </div>
          )}

          {/* LOADING OVERLAY */}
          {processing && (
            <div className="absolute inset-0 bg-white/90 backdrop-blur-sm z-50 flex flex-col items-center justify-center rounded-2xl transition-all duration-300">
               <Loader2 className="animate-spin w-12 h-12 text-blue-600 mb-4" />
               <div className="text-blue-900 font-bold text-lg animate-pulse">Running Agent Workflow...</div>
               <div className="text-slate-500 text-sm mt-2">Step {activeTab + 1}: Executing Logic</div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
};

export default WorkflowVisualizer;